apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgCXMrEre3dULqmzYwOicbwblboFaX4alRAQg8CYlLzyssfL89N+TxlgNG0M6cKRPLP8YTR5MZzIdd0mB2m2bpkAJjGvNFO7SQq6CR454Ms1/fMdsaPi0MRiIF27yuNodhg6V691B712ynz/sL0rUOKGu6fQX+R1krUGg+MPyJ4AtnyiyhJX/W0AMr2TEBEMBEQ152S9CCBZ45Q1YYHiLuPFxPrJD1pWY7t320QxW9SdokN9zKycJEQdookTBdsY8RvWA6FWYRIL/Eg3/4r8driCfIAku2MbZuxwxQZAkaup6p9K+WmsDBOfQPJj/cJsspvxvZyv2E46NZuGrfVVnHWraKcSQerenRaTG8QmTPmoenv0u8EsDdxlMpTIHPLNIk5ljAhiHRmjPUWiHw7LVmzctDGgLGkEjoI8udeK3R0annvIlbWUFglT6EABx+1qYergdje0lokGxsUCZcRBwAhCHM8YtA1ikvfjR6So7A1LEdLP6bZlAe0DqXGsSWseBYXx986WdvMIVdb5qebnyYr+Dxbxby7PTUPUbORvnDjoRToww0KwJTduQ7cbns9FyZwk+RWx3D2zCF/NILqvEw8dSB17g70h1vdSP/pKbnkQPHTPMuK38EMqysvamnC9r1PV5fQv7CxrNCT0GENtoJps98Gh9cNZYk7d7d9c+k9682cfRdXdWq3jT+2slgerpp3zVVfJ5jIXAg==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

